name: AI Agent Workflow

on:
  workflow_dispatch:

jobs:
  generate_post:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Pobranie repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Krok 2: Instalacja zależności
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install torch transformers sentencepiece

      # Krok 3: Commit i push nowego posta
      - name: Login and donwload llm
        run: |
          pip install huggingface_hub
          huggingface-cli login
          git lfs install
          git clone https://huggingface.co/meta-llama/Llama-2-7b-hf


      # Krok 4: Generowanie posta za pomocą LLaMA 2
      - name: Generate blog post
        run: |
          python scripts/generate_post.py

      # Krok 5: Commit i push nowego posta
      - name: Commit and push changes
        run: |
          git config user.name "AI Agent"
          git config user.email "ai-agent@github.com"
          git add posts/
          git commit -m "Dodano nowy post wygenerowany przez AI"
          git push